[build-system]
requires = ["flit_core>=3.12,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "boring-math-probability-distributions"
version = "1.1.0"
description = "Visualizing probability distributions."
readme = "README.md"
requires-python = ">=3.13"  # syntactic floor: known to SyntaxError below this
authors = [
  { name = "Geoffrey R. Scheller", email = "geoffrey@scheller.com" },
]
keywords = [
  "distribution",
  "probability distributions",
  "sample data",
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Framework :: Pytest",
  "Intended Audience :: Education",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.14",  # tested: pytest test suite successful
  "Typing :: Typed",
]
dependencies = [
  "matplotlib >= 3.10.1",
  "pythonic-fp.fptools >= 5.4.0",
  "boring-math-special-functions >= 5.0.0",
]

[project.urls]
Changelog = "https://github.com/grscheller/boring-math-probability-distributions/blob/main/CHANGELOG.md"
Documentation ="https://grscheller.github.io/boring-math-probability-distributions/release/html/"
Homepage = "https://grscheller.github.io/boring-math/"
Source = "https://github.com/grscheller/boring-math-probability-distributions"

[dependency-groups]
docs = [
  "furo>=2025.12.19",
  "sphinx>=9.1",
]
pub = [
  "flit",
]
test = [
  "pytest>=8.4.1",
  "numpy>=2.4.4",
  "scipy>=1.17.1",
]

[tool.flit.module]
name = "boring_math.probability_distributions"

[tool.flit.sdist]
exclude = [
  "docs/",
  "explore/",
  "tests/",
]

[tool.pytest]
addopts = ["-ra"]
consider_namespace_packages = true
testpaths = ["tests/"]

[tool.mypy]
explicit_package_bases = true
local_partial_types = true
namespace_packages = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true

[tool.ruff]
target-version = "py314"

[tool.ruff.lint]
ignore = ["RUF022", "E741"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "E731",
  "C901",
]

[tool.ruff.format]
quote-style = "single"
docstring-code-line-length = 72
